name: Bug report
description: Report a problem you're experiencing
labels: [ bug,unconfirmed ]
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search the existing issues (both open and closed).

        ---

        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
  - type: input
    id: filament-version
    attributes:
      label: Filament Version
      description: Please provide the full version of Filament you have installed.
      placeholder: v3.0.27
    validations:
      required: true
  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: Please provide the full version of the plugin you have installed.
      placeholder: v3.0.0
    validations:
      required: true
  - type: input
    id: php-version
    attributes:
      label: PHP Version
      description: Please provide the full PHP version of your server.
      placeholder: PHP 8.1.0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Problem description
      description: What happened when you experienced the problem?
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: Expected behavior
      description: What did you expect to happen instead?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Which steps do we need to take to reproduce the problem? Any code examples need to be **as short as possible**, remove any code that is unrelated to the bug.
    validations:
      required: true
  - type: input
    id: reproduction
    attributes:
      label: Reproduction repository
      description: The URL of a public GitHub repository which reproduces the problem. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn\'t matter if your real project is private / confidential, since we want a link to a separate, isolated reproduction. This allows us to fix the problem much quicker. **Please make sure to format the URL starting with `https://github.com` - only repositories hosted on GitHub are accepted.**
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, provide relevant log output. No need for backticks here.
      render: shell
