<?php

return [
    'accepted_file_types' => ['image/jpeg', 'image/png', 'image/webp', 'image/svg+xml', 'application/pdf'],
    'cloud_disks' => ['s3', 'cloudinary', 'imgix'],
    'curation_presets' => [],
    'directory' => 'media',
    'disk_name' => 'public',
    'glide_server_factory' => \Awcodes\Curator\Glide\DefaultServerFactory::class,
    'glider_fallbacks' => [],
    'image_crop_aspect_ratio' => null,
    'image_resize_mode' => null,
    'image_resize_target_height' => null,
    'image_resize_target_width' => null,
    'is_limited_to_directory' => false,
    'max_size' => 5000,
    'max_width' => 2000,
    'media_model' => \Awcodes\Curator\Models\Media::class,
    'media_resource' => \Awcodes\Curator\Resources\MediaResource::class,
    'min_size' => 0,
    'model_label' => 'Media',
    'model_plural_label' => 'Media',
    'navigation_group' => null,
    'navigation_icon' => 'heroicon-o-photo',
    'navigation_sort' => null,
    'path_generator' => null,
    'should_preserve_filenames' => false,
    'should_register_navigation' => true,
    'table_has_grid_layout' => true,
    'table_has_icon_actions' => false,
    'visibility' => 'public',
];
