name: Fix PHP code styling

on:
  pull_request:
    branches: [ 2.x ]
    types: [ closed ]

jobs:
  php-code-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 2.x

      - name: Fix PHP code style issues
        uses: aglipanci/laravel-pint-action@2.3.0

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
